package com.example.ui

object UiLocalizer {
    val keys = listOf(
        "Sync Translator",
        "Standard Mode",
        "Conversation",
        "Translation Mode Mods",
        "AI TRANSLATION STYLE / TONE:",
        "CONVERSATION TOPIC SCENARIO:",
        "Saved History",
        "All",
        "Favorites",
        "Clear All",
        "Listening:",
        "Type here or press Mic to talk in",
        "Your synchronized translation result will instantly appear here...",
        "Recording...",
        "Tap to Speak",
        "No favorites stored yet",
        "No local translation history",
        "Bilateral Conversation Mode",
        "Tap either microphone below to speak and translate. Conversational replies are spoken back out loud and saved.",
        "Bookmark",
        "Pronounce",
        "Language",
        "App Language",
        "Direct", "Casual", "Formal", "Poetic",
        "General", "Travel", "Dining", "Shopping", "Medical",
        "Split-Earbud Mode",
        "Please connect Bluetooth headphones to activate split audio routing.",
        "Bluetooth headphones detected! Stereo split pan is active.",
        "Right Earbud: Target language",
        "Left Earbud: Source language"
    )

    private val es = mapOf(
        "Sync Translator" to "Traductor Sync",
        "Standard Mode" to "Modo Estándar",
        "Conversation" to "Conversación",
        "Translation Mode Mods" to "Mods de Traducción",
        "AI TRANSLATION STYLE / TONE:" to "ESTILO / TONO DE TRADUCCIÓN IA:",
        "CONVERSATION TOPIC SCENARIO:" to "ESTRECHAS DE DIÁLOGO / TEMA:",
        "Saved History" to "Historial Guardado",
        "All" to "Todos",
        "Favorites" to "Favoritos",
        "Clear All" to "Limpiar Todo",
        "Listening:" to "Escuchando:",
        "Type here or press Mic to talk in" to "Escribe aquí o pulsa el Micrófono en",
        "Your synchronized translation result will instantly appear here..." to "El resultado aparecerá instantáneamente aquí...",
        "Recording..." to "Grabando...",
        "Tap to Speak" to "Toca para Hablar",
        "No favorites stored yet" to "Aún sin favoritos guardados",
        "No local translation history" to "Sin historial local de traducciones",
        "Bilateral Conversation Mode" to "Modo Conversación Bilateral",
        "Tap either microphone below to speak and translate. Conversational replies are spoken back out loud and saved." to "Toca un micrófono abajo para hablar. Las respuestas se reproducen y se guardan automáticamente.",
        "Bookmark" to "Guardar como favorito",
        "Pronounce" to "Pronunciar",
        "Language" to "Idioma",
        "App Language" to "Idioma de la App",
        "Direct" to "Directo",
        "Casual" to "Informal",
        "Formal" to "Formal",
        "Poetic" to "Poético",
        "General" to "General",
        "Travel" to "Viaje",
        "Dining" to "Restaurantes",
        "Shopping" to "Compras",
        "Medical" to "Médico",
        "Split-Earbud Mode" to "Modo Auricular Dividido",
        "Please connect Bluetooth headphones to activate split audio routing." to "Por favor conecta auriculares Bluetooth para activar la ruta dividida de audio.",
        "Bluetooth headphones detected! Stereo split pan is active." to "¡Auriculares Bluetooth detectados! El balance estéreo dividido está activo.",
        "Right Earbud: Target language" to "Auricular Derecho: Idioma destino",
        "Left Earbud: Source language" to "Auricular Izquierdo: Idioma origen"
    )

    private val hy = mapOf(
        "Sync Translator" to "Սինք Թարգմանիչ",
        "Standard Mode" to "Ստանդարտ Ռեժիմ",
        "Conversation" to "Զրույց",
        "Translation Mode Mods" to "Թարգմանության Օպցիաներ",
        "AI TRANSLATION STYLE / TONE:" to "ՄԱ ԹԱՐԳՄԱՆՈՒԹՅԱՆ ՈՃԸ՝",
        "CONVERSATION TOPIC SCENARIO:" to "ԶՐՈՒՅՑԻ ԹԵՄԱՆ / ՍՑԵՆԱՐ՝",
        "Saved History" to "Պահպանված Պատմություն",
        "All" to "Բոլորը",
        "Favorites" to "Աստղանշված",
        "Clear All" to "Մաքրել Բոլորը",
        "Listening:" to "Լսում է՝",
        "Type here or press Mic to talk in" to "Գրեք այստեղ կամ սեղմեք Միկրոֆոնը",
        "Your synchronized translation result will instantly appear here..." to "Ձեր թարգմանության արդյունքը կհայտնվի այստեղ...",
        "Recording..." to "Ձայնագրում...",
        "Tap to Speak" to "Հպվեք խոսելու համար",
        "No favorites stored yet" to "Դեռևս չկան աստղանշված թարգմանություններ",
        "No local translation history" to "Տեղական պատմությունը դատարկ է",
        "Bilateral Conversation Mode" to "Երկկողմանի Զրույցի Ռեժիմ",
        "Tap either microphone below to speak and translate. Conversational replies are spoken back out loud and saved." to "Խոսելու համար սեղմեք ներքևի միկրոֆոններից մեկը։",
        "Bookmark" to "Պահել",
        "Pronounce" to "Արտասանել",
        "Language" to "Լեզու",
        "App Language" to "Հավելվածի Լեզուն",
        "Direct" to "Ուղղակի",
        "Casual" to "Ընկերական",
        "Formal" to "Պաշտոնական",
        "Poetic" to "Պոետիկ",
        "General" to "Ընդհանուր",
        "Travel" to "Ճամփորդություն",
        "Dining" to "Սննդի ոլորտ",
        "Shopping" to "Գնումներ",
        "Medical" to "Բժշկական",
        "Split-Earbud Mode" to "Ականջակալների Բաժանման Ռեժիմ",
        "Please connect Bluetooth headphones to activate split audio routing." to "Խնդրում ենք միացնել Bluetooth ականջակալներ՝ ձայնի բաժանումն ակտիվացնելու համար:",
        "Bluetooth headphones detected! Stereo split pan is active." to "Bluetooth ականջակալները հայտնաբերված են: Ստերեո բաժանումն ակտիվ է:",
        "Right Earbud: Target language" to "Աջ ականջակալ՝ Թիրախ լեզու",
        "Left Earbud: Source language" to "Ձախ ականջակալ՝ Մայր լեզու"
    )

    private val ru = mapOf(
        "Sync Translator" to "Синхронный переводчик",
        "Standard Mode" to "Стандартный режим",
        "Conversation" to "Разговор",
        "Translation Mode Mods" to "Опции перевода",
        "AI TRANSLATION STYLE / TONE:" to "СТИЛЬ И ТОН ИИ-ПЕРЕВОДА:",
        "CONVERSATION TOPIC SCENARIO:" to "КОНТЕКСТ СЦЕНАРИЯ ДИАЛОГА:",
        "Saved History" to "Сохранённая история",
        "All" to "Все",
        "Favorites" to "Избранное",
        "Clear All" to "Очистить всё",
        "Listening:" to "Прослушивание:",
        "Type here or press Mic to talk in" to "Пишите здесь или нажмите микрофон для",
        "Your synchronized translation result will instantly appear here..." to "Результат перевода появится здесь...",
        "Recording..." to "Запись...",
        "Tap to Speak" to "Начать говорить",
        "No favorites stored yet" to "Список избранного пуст",
        "No local translation history" to "Локальная история пуста",
        "Bilateral Conversation Mode" to "Двусторонний режим диалога",
        "Tap either microphone below to speak and translate. Conversational replies are spoken back out loud and saved." to "Нажмите на микрофон внизу для синхронного перевода.",
        "Bookmark" to "Добавить",
        "Pronounce" to "Озвучить",
        "Language" to "Язык",
        "App Language" to "Язык приложения",
        "Direct" to "Прямой",
        "Casual" to "Разговорный",
        "Formal" to "Официальный",
        "Poetic" to "Поэтичный",
        "General" to "Общий",
        "Travel" to "Путешествия",
        "Dining" to "Кафе и рестораны",
        "Shopping" to "Покупки",
        "Medical" to "Медицина",
        "Split-Earbud Mode" to "Раздельный режим наушников",
        "Please connect Bluetooth headphones to activate split audio routing." to "Пожалуйста, подключите Bluetooth-наушники для активации раздельного аудио.",
        "Bluetooth headphones detected! Stereo split pan is active." to "Bluetooth-наушники обнаружены! Раздельное стерео-направление активно.",
        "Right Earbud: Target language" to "Правый наушник: Целевой язык",
        "Left Earbud: Source language" to "Левый наушник: Исходный язык"
    )

    private val fr = mapOf(
        "Sync Translator" to "Traducteur Sync",
        "Standard Mode" to "Mode Standard",
        "Conversation" to "Conversation",
        "Translation Mode Mods" to "Options de Traduction",
        "AI TRANSLATION STYLE / TONE:" to "STYLE / TONALITÉ IA :",
        "CONVERSATION TOPIC SCENARIO:" to "THÉMATIQUE DU DIALOGUE :",
        "Saved History" to "Historique",
        "All" to "Tout",
        "Favorites" to "Favoris",
        "Clear All" to "Tout effacer",
        "Listening:" to "Écoute...",
        "Type here or press Mic to talk in" to "Écrivez ou appuyez pour parler en",
        "Your synchronized translation result will instantly appear here..." to "Le résultat de traduction s'affichera ici...",
        "Recording..." to "Enregistrement...",
        "Tap to Speak" to "Appuyez pour Parler",
        "No favorites stored yet" to "Aucun favori enregistré",
        "No local translation history" to "Aucun historique local",
        "Bilateral Conversation Mode" to "Mode Conversation Bilatérale",
        "Tap either microphone below to speak and translate. Conversational replies are spoken back out loud and saved." to "Parlez dans l'un des micros ci-dessous.",
        "Bookmark" to "Favoris",
        "Pronounce" to "Prononcer",
        "Language" to "Langue",
        "App Language" to "Langue de l'app",
        "Direct" to "Direct",
        "Casual" to "Familier",
        "Formal" to "Soutenu",
        "Poetic" to "Poétique",
        "General" to "Général",
        "Travel" to "Voyage",
        "Dining" to "Restauration",
        "Shopping" to "Achats",
        "Medical" to "Médical",
        "Split-Earbud Mode" to "Mode Oreillette Séparé",
        "Please connect Bluetooth headphones to activate split audio routing." to "Veuillez connecter des écouteurs Bluetooth pour activer le routage d'écouteurs séparés.",
        "Bluetooth headphones detected! Stereo split pan is active." to "Écouteurs Bluetooth détectés ! Le routage stéréo séparé est actif.",
        "Right Earbud: Target language" to "Oreillette Droite : Langue cible",
        "Left Earbud: Source language" to "Oreillette Gauche : Langue source"
    )

    private val de = mapOf(
        "Sync Translator" to "Sync Übersetzer",
        "Standard Mode" to "Standardmodus",
        "Conversation" to "Konversation",
        "Translation Mode Mods" to "Optionen",
        "AI TRANSLATION STYLE / TONE:" to "KI ÜBERSETZUNGSSTIL / TON:",
        "CONVERSATION TOPIC SCENARIO:" to "DIALOG THEMA:",
        "Saved History" to "Verlauf",
        "All" to "Alle",
        "Favorites" to "Favoriten",
        "Clear All" to "Alle löschen",
        "Listening:" to "Zuhören...",
        "Type here or press Mic to talk in" to "Tippen oder sprechen auf",
        "Your synchronized translation result will instantly appear here..." to "Ergebnis erscheint hier...",
        "Recording..." to "Aufnahme...",
        "Tap to Speak" to "Sprechen",
        "No favorites stored yet" to "Noch keine Favoriten vorhanden",
        "No local translation history" to "Kein lokaler Verlauf vorhanden",
        "Bilateral Conversation Mode" to "Zweiseitiger Dialogmodus",
        "Tap either microphone below to speak and translate. Conversational replies are spoken back out loud and saved." to "Tippen Sie auf ein Mikrofon unten.",
        "Bookmark" to "Merken",
        "Pronounce" to "Vorsprechen",
        "Language" to "Sprache",
        "App Language" to "App-Sprache",
        "Direct" to "Direkt",
        "Casual" to "Locker",
        "Formal" to "Formell",
        "Poetic" to "Poetisch",
        "General" to "Allgemein",
        "Travel" to "Reisen",
        "Dining" to "Gastronomie",
        "Shopping" to "Einkaufen",
        "Medical" to "Medizinisch",
        "Split-Earbud Mode" to "Geteilter Kopfhörer-Modus",
        "Please connect Bluetooth headphones to activate split audio routing." to "Bitte verbinden Sie Bluetooth-Kopfhörer, um das geteilte Audio-Routing zu aktivieren.",
        "Bluetooth headphones detected! Stereo split pan is active." to "Bluetooth-Kopfhörer erkannt! Geteiltes Stereo-Routing ist aktiv.",
        "Right Earbud: Target language" to "Rechter Hörer: Zielsprache",
        "Left Earbud: Source language" to "Linker Hörer: Ausgangssprache"
    )

    private val fallbackMaps = mapOf(
        "es" to es,
        "hy" to hy,
        "ru" to ru,
        "fr" to fr,
        "de" to de
    )

    fun getFallback(langCode: String): Map<String, String>? {
        return fallbackMaps[langCode]
    }
}
